location:
  latitude: 42.4883417
  longitude: -71.2235583
  radius_meters: 15000.0

processing:
  months_threshold: 6
  reprocess_all: false
  save_negative_images: false

place_types:
  - bar
  - hotel
  - restaurant 